name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        conda-channel: ['conda-forge', 'conda-canary/label/dev']
        include:
          # Lowest versions to test for.
          - conda-channel: 'conda-forge'
            conda-build-version: '3.25'
            python-version: '3.8'
          # Unbound/dev versions to test for.
          - conda-channel: 'conda-canary/label/dev'
            conda-build-version: '*'
            python-version: '*'
    steps:
    - uses: actions/checkout@v4
    - name: install mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/env.yml
        create-args: >-
          --channel-priority=flexible
          python=${{ matrix.python-version }}
          ${{ matrix.conda-channel }}::conda
          ${{ matrix.conda-channel }}::conda-build=${{ matrix.conda-build-version }}
    - name: Install boa
      shell: bash -l {0}
      run: |
        pip install .
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        pytest tests
      env:
        PYTHONUTF8: 1
